################################# Default configuration ###################
# provide your domain here
 baseURL = "https://crpl.cis.udel.edu/oaccvv"
# theme
theme = "dot-hugo"
# site title
title = "OpenACC V&V"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
# [markup.goldmark.renderer]
# unsafe = true
 
staticDir = ['static']

languageCode = "en-us"


relativeURLS = true
canonifyurls = true

[markup.goldmark.renderer]
unsafe = true

############################# Default Parameters ##########################
[Params]
# logo is for all page
logo = "/images/OpenACCVVdark.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "/images/OpenACCVVwhite.png"
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "The OpenACC Validation and Verification Testsuite"
author = "OpenACC V&V"
image = "static/images/openacc_logo.svg" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#122654"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#fff"
light_color = "#f8f9fa"
dark_blue = "#122654"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter CRPL"
link = "https://twitter.com/crpl_hpc?lang=el"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter AJ"
link = "https://twitter.com/aaronjarmusch?lang=en"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/OpenACCUserGroup/OpenACCV-V"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
name = "Linkedin"
link = "https://www.linkedin.com/in/aaron-jarmusch-1174981b1"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; 2022; Theme made for OpenACC V&V"

# banner
[Languages.en.params.banner]
title = "OpenACC Verification and Validation Testsuite"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# welcome
[Languages.en.params.welcome]
enable = true
title = "Welcome"
content = "This website contains information about the OpenACC V&V testsuite. This work is in collaboration with OpenACC/NVIDIA/Mentor Graphics. Any project related questions, please mail Aaron Jarmusch (Jarmusch@udel.edu) or Sunita Chandrasekaran (schandra@udel.edu)."

# call to action
[Languages.en.params.cta]
enable = true
title = "Just ask. Get answers."
content = "Your questions and comments are important to us."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = ""
weight = 1

[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Publications"
url = "about/publications/"
weight = 3

[[Languages.en.menu.main]]
name = "Results"
url = "archieve"
weight = 4

[[Languages.en.menu.main]]
name = "Github"
url = "github"
weight = 5

# Dropdown menu
[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 6

[[Languages.en.menu.main]]
name = "CRPL"
url = "https://crpl.cis.udel.edu"
weight = 7
#hasChildren = true

  # [[Languages.en.menu.main]]
  # parent = "project"
  # name = "Installation"
  # url = "installation"
  # weight = 1

  # [[Languages.en.menu.main]]
  # parent = "project"
  # name = "Requirments"
  # url = "requirments"
  # weight = 2

  # [[Languages.en.menu.main]]
  # parent = "project"
  # name = "Elements"
  # url = "elements"
  # weight = 3
